# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Design_DB.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Db_Window(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(590, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Author_line = QtWidgets.QLineEdit(self.centralwidget)
        self.Author_line.setGeometry(QtCore.QRect(30, 70, 113, 20))
        self.Author_line.setObjectName("Author_line")
        self.Music_line = QtWidgets.QLineEdit(self.centralwidget)
        self.Music_line.setGeometry(QtCore.QRect(30, 130, 113, 20))
        self.Music_line.setObjectName("Music_line")
        self.resultDBTable = QtWidgets.QTableWidget(self.centralwidget)
        self.resultDBTable.setGeometry(QtCore.QRect(190, 50, 311, 341))
        self.resultDBTable.setStyleSheet("style{qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 255, 255, 255), stop:0.1 rgba(255, 255, 255, 255), stop:0.2 rgba(255, 176, 176, 167), stop:0.3 rgba(255, 151, 151, 92), stop:0.4 rgba(255, 125, 125, 51), stop:0.5 rgba(255, 76, 76, 205), stop:0.52 rgba(255, 76, 76, 205), stop:0.6 rgba(255, 180, 180, 84), stop:1 rgba(255, 255, 255, 0))}")
        self.resultDBTable.setObjectName("resultDBTable")
        self.resultDBTable.setColumnCount(3)
        self.resultDBTable.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.resultDBTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultDBTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultDBTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultDBTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultDBTable.setHorizontalHeaderItem(2, item)
        self.searchButton = QtWidgets.QPushButton(self.centralwidget)
        self.searchButton.setGeometry(QtCore.QRect(44, 190, 81, 31))
        self.searchButton.setObjectName("searchButton")
        self.addToPlaylistButton = QtWidgets.QPushButton(self.centralwidget)
        self.addToPlaylistButton.setGeometry(QtCore.QRect(30, 260, 111, 41))
        self.addToPlaylistButton.setObjectName("addToPlaylistButton")
        self.NameAuthor = QtWidgets.QLabel(self.centralwidget)
        self.NameAuthor.setGeometry(QtCore.QRect(30, 30, 91, 31))
        self.NameAuthor.setObjectName("NameAuthor")
        self.NameMusic = QtWidgets.QLabel(self.centralwidget)
        self.NameMusic.setGeometry(QtCore.QRect(30, 90, 91, 31))
        self.NameMusic.setObjectName("NameMusic")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DataBase"))
        item = self.resultDBTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.resultDBTable.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.resultDBTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "id"))
        item = self.resultDBTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Author"))
        item = self.resultDBTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Music"))
        self.searchButton.setText(_translate("MainWindow", "Найти"))
        self.addToPlaylistButton.setText(_translate("MainWindow", "Внести в плейлист"))
        self.NameAuthor.setText(_translate("MainWindow", "Имя автора:"))
        self.NameMusic.setText(_translate("MainWindow", "Название песни:"))
