# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Design_DB.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Db_Window(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(590, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.PlaylistLine = QtWidgets.QLineEdit(self.centralwidget)
        self.PlaylistLine.setGeometry(QtCore.QRect(160, 70, 113, 20))
        self.PlaylistLine.setObjectName("PlaylistLine")
        self.addToPlaylistButton = QtWidgets.QPushButton(self.centralwidget)
        self.addToPlaylistButton.setGeometry(QtCore.QRect(420, 62, 121, 31))
        self.addToPlaylistButton.setObjectName("addToPlaylistButton")
        self.NamePlaylist = QtWidgets.QLabel(self.centralwidget)
        self.NamePlaylist.setGeometry(QtCore.QRect(160, 30, 111, 21))
        self.NamePlaylist.setObjectName("NamePlaylist")
        self.dbTable = QtWidgets.QTableWidget(self.centralwidget)
        self.dbTable.setGeometry(QtCore.QRect(60, 170, 511, 271))
        self.dbTable.setObjectName("dbTable")
        self.dbTable.setColumnCount(5)
        self.dbTable.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.dbTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.dbTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.dbTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.dbTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.dbTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.dbTable.setHorizontalHeaderItem(4, item)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DataBase"))
        self.addToPlaylistButton.setText(_translate("MainWindow", "Добавить в плейлист"))
        self.NamePlaylist.setText(_translate("MainWindow", "Название плейлиста"))
        item = self.dbTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.dbTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "id"))
        item = self.dbTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Author"))
        item = self.dbTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Music"))
        item = self.dbTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Path"))
        item = self.dbTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Playlist"))
